
{% set name = "spatialpy" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ba4dfa018bede9e5ee1d8657898e54b85b7c117d815d47056824a864e603796
  
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  
requirements:
  host:
    - python >3.5
    - pip
    - setuptools >=41.0.1
    
  run:
    - python >3.5
    - matplotlib >=3.0.3
    - plotly >=4.1.0
    - scipy >=1.4.1
    - meshio >=5.3.2
    
test:
  imports:
    - spatialpy
     
about:
  home: https://github.com/StochSS/SpatialPy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'SpatialPy is a Python 3 package for simulation of spatial deterministic/stochastic reaction-diffusion-advection problems embedded in Lagrangian reference frame particle based fluid dynamics domain'

  description: |
    SpatialPy is a Python 3 package for simulation of spatial deterministic/stochastic reaction-diffusion-advection problems embedded in Lagrangian reference frame particle based fluid dynamics domain
    This package is intended to replace the PyURDME software https://github.com/pyurdme/pyurdme and will feature both a NSM solver for RDME simulation on static domains and a sSSA-SDPD particle based fluid dynamics solver as described in the publication "A hybrid smoothed dissipative particle dynamics (SDPD) spatial stochastic simulation algorithm (sSSA) for advection–diffusion–reaction problems" by Drawert, Jacob, Li, Yi, Petzold https://www.sciencedirect.com/science/article/pii/S0021999118307101
    
  dev_url: https://github.com/StochSS/SpatialPy

extra:
  recipe-maintainers:
    - briandrawert
    - seanebum
    - BryanRumsey
